version: '3'

services:
    typademic:
        container_name: typademic
        # uncomment this line for production use
        # image: maehr/typademic:latest

        # comment this line for production use
        build: .
        ports:
            - 8501:8501
