version: '2'

services:
  typademic:
    container_name: typademic
    # uncomment this line for production use
    image: maehr/typademic:latest

    # comment this line for production use
    # build: .

    ports:
      - "443:8000"

    volumes:
      - ./logs/error.log:/logs/error.log
      - ./logs/access.log:/logs/access.log
      - ./uploads/:/uploads/

    restart: always

    # uncomment this line for production use
    env_file: ./secrets.env

    # comment this line for production use
    #environment:
    #  - SECRET_KEY=${SECRET_KEY}
