name: code-check
on: [push]

jobs:
    code-check:
        strategy:
            fail-fast: flase
            matrix:
                python-version: [3.9]
                poetry-version: [1.1.8]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: { { matrix.python-version } }
            - uses: abatilo/actions-poetry@v2.0.0
              with:
                  poetry-version: { { matrix.poetry-version } }
            - run: poetry install
            - name: black
              run: poetry run black . --check
            - name: isort
              run: poetry run isort . --check-only --profile black
            - name: flake8
              run: poetry run flake8 .
            - name: bandit
              run: poetry run bandit .
            - name: safety
              run: poetry run safety check
